# This is a basic workflow to help you get started with Actions

name: CI Test

on:
  push:
    branches: [ master ]

jobs:
  run-mvn-test:
    name: ${{ matrix.distribution }} ${{ matrix.version }} (jdk-x64) - ${{ matrix.os }} - Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        distribution: [ 'adopt', 'zulu' ]
        version: [ '8', '11' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.version }}
          distribution: ${{ matrix.distribution }}
      - name: Compile code
        run: mvn test
